package com.xupt.read.mapper;

import com.xupt.read.model.Bookshelf;
import com.xupt.read.model.BookshelfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookshelfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    long countByExample(BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    int deleteByExample(BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    int insert(Bookshelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    int insertSelective(Bookshelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    List<Bookshelf> selectByExample(BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    Bookshelf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") Bookshelf record, @Param("example") BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    int updateByExample(@Param("record") Bookshelf record, @Param("example") BookshelfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    int updateByPrimaryKeySelective(Bookshelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    int updateByPrimaryKey(Bookshelf record);
}