package com.xupt.read.mapper;

import com.xupt.read.model.BookType;
import com.xupt.read.model.BookTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    long countByExample(BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    int deleteByExample(BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    int insert(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    int insertSelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    List<BookType> selectByExample(BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    BookType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    int updateByExampleSelective(@Param("record") BookType record, @Param("example") BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    int updateByExample(@Param("record") BookType record, @Param("example") BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    int updateByPrimaryKeySelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_types
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    int updateByPrimaryKey(BookType record);
}