package com.xupt.read.mapper;

import com.xupt.read.model.BrowseRecord;
import com.xupt.read.model.BrowseRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrowseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    long countByExample(BrowseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    int deleteByExample(BrowseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    int insert(BrowseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    int insertSelective(BrowseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    List<BrowseRecord> selectByExample(BrowseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    BrowseRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    int updateByExampleSelective(@Param("record") BrowseRecord record, @Param("example") BrowseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    int updateByExample(@Param("record") BrowseRecord record, @Param("example") BrowseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    int updateByPrimaryKeySelective(BrowseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_records
     *
     * @mbg.generated Wed Nov 16 01:09:17 CST 2022
     */
    int updateByPrimaryKey(BrowseRecord record);
}