package com.xupt.read.model;

import java.io.Serializable;
import java.util.Date;

public class Bookshelf implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.user_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.book_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.created_at
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookshelf
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.id
     *
     * @return the value of bookshelf.id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.id
     *
     * @param id the value for bookshelf.id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.user_id
     *
     * @return the value of bookshelf.user_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.user_id
     *
     * @param userId the value for bookshelf.user_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.book_id
     *
     * @return the value of bookshelf.book_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.book_id
     *
     * @param bookId the value for bookshelf.book_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.created_at
     *
     * @return the value of bookshelf.created_at
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.created_at
     *
     * @param createdAt the value for bookshelf.created_at
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}