package com.xupt.read.model;

import java.io.Serializable;

public class Bookshelf implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.id
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.user_id
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.book_id
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelf.book_content
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    private String bookContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookshelf
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.id
     *
     * @return the value of bookshelf.id
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.id
     *
     * @param id the value for bookshelf.id
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.user_id
     *
     * @return the value of bookshelf.user_id
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.user_id
     *
     * @param userId the value for bookshelf.user_id
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.book_id
     *
     * @return the value of bookshelf.book_id
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.book_id
     *
     * @param bookId the value for bookshelf.book_id
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelf.book_content
     *
     * @return the value of bookshelf.book_content
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    public String getBookContent() {
        return bookContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelf.book_content
     *
     * @param bookContent the value for bookshelf.book_content
     *
     * @mbg.generated Sun Apr 19 18:59:54 CST 2020
     */
    public void setBookContent(String bookContent) {
        this.bookContent = bookContent == null ? null : bookContent.trim();
    }
}