package com.xupt.read.model;

import java.io.Serializable;
import java.util.Date;

public class Bookshelf implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelves.id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelves.user_id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelves.book_id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelves.create_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookshelves.update_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookshelves
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelves.id
     *
     * @return the value of bookshelves.id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelves.id
     *
     * @param id the value for bookshelves.id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelves.user_id
     *
     * @return the value of bookshelves.user_id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelves.user_id
     *
     * @param userId the value for bookshelves.user_id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelves.book_id
     *
     * @return the value of bookshelves.book_id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelves.book_id
     *
     * @param bookId the value for bookshelves.book_id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelves.create_time
     *
     * @return the value of bookshelves.create_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelves.create_time
     *
     * @param createTime the value for bookshelves.create_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookshelves.update_time
     *
     * @return the value of bookshelves.update_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookshelves.update_time
     *
     * @param updateTime the value for bookshelves.update_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}