package com.xupt.read.model;

import java.io.Serializable;
import java.util.Date;

public class BrowseRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browse_record.id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browse_record.user_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browse_record.book_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browse_record.create_at
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table browse_record
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browse_record.id
     *
     * @return the value of browse_record.id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browse_record.id
     *
     * @param id the value for browse_record.id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browse_record.user_id
     *
     * @return the value of browse_record.user_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browse_record.user_id
     *
     * @param userId the value for browse_record.user_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browse_record.book_id
     *
     * @return the value of browse_record.book_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browse_record.book_id
     *
     * @param bookId the value for browse_record.book_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browse_record.create_at
     *
     * @return the value of browse_record.create_at
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browse_record.create_at
     *
     * @param createAt the value for browse_record.create_at
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}