package com.xupt.read.model;

import java.io.Serializable;

public class Circle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.user_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.book_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.comment
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.coefficient
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private Integer coefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.id
     *
     * @return the value of circle.id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.id
     *
     * @param id the value for circle.id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.user_id
     *
     * @return the value of circle.user_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.user_id
     *
     * @param userId the value for circle.user_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.book_id
     *
     * @return the value of circle.book_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.book_id
     *
     * @param bookId the value for circle.book_id
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.comment
     *
     * @return the value of circle.comment
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.comment
     *
     * @param comment the value for circle.comment
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.coefficient
     *
     * @return the value of circle.coefficient
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public Integer getCoefficient() {
        return coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.coefficient
     *
     * @param coefficient the value for circle.coefficient
     *
     * @mbg.generated Sun Apr 19 16:12:11 CST 2020
     */
    public void setCoefficient(Integer coefficient) {
        this.coefficient = coefficient;
    }
}