package com.xupt.read.model;

import java.io.Serializable;
import java.util.Date;

public class Circle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.id
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.user_id
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.book_id
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.pictures
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private String pictures;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.comment
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.coefficient
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private Integer coefficient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.location
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.is_delete
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.created_at
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle.uodate_at
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private Date uodateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.id
     *
     * @return the value of circle.id
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.id
     *
     * @param id the value for circle.id
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.user_id
     *
     * @return the value of circle.user_id
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.user_id
     *
     * @param userId the value for circle.user_id
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.book_id
     *
     * @return the value of circle.book_id
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.book_id
     *
     * @param bookId the value for circle.book_id
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.pictures
     *
     * @return the value of circle.pictures
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public String getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.pictures
     *
     * @param pictures the value for circle.pictures
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public void setPictures(String pictures) {
        this.pictures = pictures == null ? null : pictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.comment
     *
     * @return the value of circle.comment
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.comment
     *
     * @param comment the value for circle.comment
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.coefficient
     *
     * @return the value of circle.coefficient
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public Integer getCoefficient() {
        return coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.coefficient
     *
     * @param coefficient the value for circle.coefficient
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public void setCoefficient(Integer coefficient) {
        this.coefficient = coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.location
     *
     * @return the value of circle.location
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.location
     *
     * @param location the value for circle.location
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.is_delete
     *
     * @return the value of circle.is_delete
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.is_delete
     *
     * @param isDelete the value for circle.is_delete
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.created_at
     *
     * @return the value of circle.created_at
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.created_at
     *
     * @param createdAt the value for circle.created_at
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle.uodate_at
     *
     * @return the value of circle.uodate_at
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public Date getUodateAt() {
        return uodateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle.uodate_at
     *
     * @param uodateAt the value for circle.uodate_at
     *
     * @mbg.generated Sat May 16 13:48:58 CST 2020
     */
    public void setUodateAt(Date uodateAt) {
        this.uodateAt = uodateAt;
    }
}