package com.xupt.read.model;

import java.io.Serializable;
import java.util.Date;

public class CircleComment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_comment.id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_comment.circle_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private Integer circleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_comment.user_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_comment.comment
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_comment.is_delete
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_comment.created_at
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column circle_comment.updated_at
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table circle_comment
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_comment.id
     *
     * @return the value of circle_comment.id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_comment.id
     *
     * @param id the value for circle_comment.id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_comment.circle_id
     *
     * @return the value of circle_comment.circle_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public Integer getCircleId() {
        return circleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_comment.circle_id
     *
     * @param circleId the value for circle_comment.circle_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setCircleId(Integer circleId) {
        this.circleId = circleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_comment.user_id
     *
     * @return the value of circle_comment.user_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_comment.user_id
     *
     * @param userId the value for circle_comment.user_id
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_comment.comment
     *
     * @return the value of circle_comment.comment
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_comment.comment
     *
     * @param comment the value for circle_comment.comment
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_comment.is_delete
     *
     * @return the value of circle_comment.is_delete
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_comment.is_delete
     *
     * @param isDelete the value for circle_comment.is_delete
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_comment.created_at
     *
     * @return the value of circle_comment.created_at
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_comment.created_at
     *
     * @param createdAt the value for circle_comment.created_at
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column circle_comment.updated_at
     *
     * @return the value of circle_comment.updated_at
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column circle_comment.updated_at
     *
     * @param updatedAt the value for circle_comment.updated_at
     *
     * @mbg.generated Wed May 20 01:20:08 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}