package com.xupt.read.model;

import java.io.Serializable;
import java.util.Date;

public class Note implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.bookshelf_id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private Integer bookshelfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.note
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.create_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.update_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notes
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.id
     *
     * @return the value of notes.id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.id
     *
     * @param id the value for notes.id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.bookshelf_id
     *
     * @return the value of notes.bookshelf_id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public Integer getBookshelfId() {
        return bookshelfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.bookshelf_id
     *
     * @param bookshelfId the value for notes.bookshelf_id
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public void setBookshelfId(Integer bookshelfId) {
        this.bookshelfId = bookshelfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.note
     *
     * @return the value of notes.note
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.note
     *
     * @param note the value for notes.note
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.create_time
     *
     * @return the value of notes.create_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.create_time
     *
     * @param createTime the value for notes.create_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.update_time
     *
     * @return the value of notes.update_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.update_time
     *
     * @param updateTime the value for notes.update_time
     *
     * @mbg.generated Sat Nov 12 16:21:53 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}