package com.xupt.read.model;

import java.io.Serializable;
import java.util.Date;

public class Note implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.id
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.bookshelf_id
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    private Integer bookshelfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.note
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.created_at
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table note
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.id
     *
     * @return the value of note.id
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.id
     *
     * @param id the value for note.id
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.bookshelf_id
     *
     * @return the value of note.bookshelf_id
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    public Integer getBookshelfId() {
        return bookshelfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.bookshelf_id
     *
     * @param bookshelfId the value for note.bookshelf_id
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    public void setBookshelfId(Integer bookshelfId) {
        this.bookshelfId = bookshelfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.note
     *
     * @return the value of note.note
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.note
     *
     * @param note the value for note.note
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.created_at
     *
     * @return the value of note.created_at
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.created_at
     *
     * @param createdAt the value for note.created_at
     *
     * @mbg.generated Sat Apr 25 18:33:59 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}