debug: false

server:
  port: 8082

spring:
  resources:
    add-mappings: false

  datasource:
    username: root
    password:
    url: jdbc:mysql://47.94.241.172:3306/stealage?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    dbcp2:
      min-idle: 10
      initial-size: 10
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      remove-abandoned-on-borrow: true
      remove-abandoned-on-maintenance: true
      connection-init-sqls: set names utf8mb4

pagehelper:
  helperDialect: mysql
  reasonable: true                #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
  supportMethodsArguments: true   #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false             #pageSize=0 返回所有
  params: count=countSql

file:
  upload:
    path: /work/project/file/upload/stealage/img/
