package com.xupt.stealage.mapper;

import com.xupt.stealage.model.CircleLike;
import com.xupt.stealage.model.CircleLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CircleLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    long countByExample(CircleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int deleteByExample(CircleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int insert(CircleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int insertSelective(CircleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    List<CircleLike> selectByExample(CircleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    CircleLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") CircleLike record, @Param("example") CircleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByExample(@Param("record") CircleLike record, @Param("example") CircleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByPrimaryKeySelective(CircleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_likes
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByPrimaryKey(CircleLike record);
}