package com.xupt.stealage.mapper;

import com.xupt.stealage.model.Circle;
import com.xupt.stealage.model.CircleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CircleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    long countByExample(CircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int deleteByExample(CircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int insert(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int insertSelective(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    List<Circle> selectByExample(CircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    Circle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") Circle record, @Param("example") CircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByExample(@Param("record") Circle record, @Param("example") CircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByPrimaryKeySelective(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circles
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByPrimaryKey(Circle record);
}