package com.xupt.stealage.mapper;

import com.xupt.stealage.model.CircleComment;
import com.xupt.stealage.model.CircleCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CircleCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    long countByExample(CircleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int deleteByExample(CircleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int insert(CircleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int insertSelective(CircleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    List<CircleComment> selectByExample(CircleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    CircleComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") CircleComment record, @Param("example") CircleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByExample(@Param("record") CircleComment record, @Param("example") CircleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByPrimaryKeySelective(CircleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circle_comments
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    int updateByPrimaryKey(CircleComment record);
}