package com.xupt.stealage.mapper;

import com.xupt.stealage.model.StealageProcessContent;
import com.xupt.stealage.model.StealageProcessContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StealageProcessContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    long countByExample(StealageProcessContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    int deleteByExample(StealageProcessContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    int insert(StealageProcessContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    int insertSelective(StealageProcessContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    List<StealageProcessContent> selectByExample(StealageProcessContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    StealageProcessContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    int updateByExampleSelective(@Param("record") StealageProcessContent record, @Param("example") StealageProcessContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    int updateByExample(@Param("record") StealageProcessContent record, @Param("example") StealageProcessContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    int updateByPrimaryKeySelective(StealageProcessContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    int updateByPrimaryKey(StealageProcessContent record);
}