package com.xupt.stealage.model;

import java.io.Serializable;
import java.util.Date;

public class Opinion implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opinions.id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opinions.user_id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opinions.content
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opinions.is_solve
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Boolean isSolve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opinions.create_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opinions.update_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table opinions
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opinions.id
     *
     * @return the value of opinions.id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opinions.id
     *
     * @param id the value for opinions.id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opinions.user_id
     *
     * @return the value of opinions.user_id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opinions.user_id
     *
     * @param userId the value for opinions.user_id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opinions.content
     *
     * @return the value of opinions.content
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opinions.content
     *
     * @param content the value for opinions.content
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opinions.is_solve
     *
     * @return the value of opinions.is_solve
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Boolean getIsSolve() {
        return isSolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opinions.is_solve
     *
     * @param isSolve the value for opinions.is_solve
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setIsSolve(Boolean isSolve) {
        this.isSolve = isSolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opinions.create_time
     *
     * @return the value of opinions.create_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opinions.create_time
     *
     * @param createTime the value for opinions.create_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opinions.update_time
     *
     * @return the value of opinions.update_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opinions.update_time
     *
     * @param updateTime the value for opinions.update_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}