package com.xupt.stealage.model;

import java.io.Serializable;
import java.util.Date;

public class Stealage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.name
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.user_id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.is_recruitment
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Boolean isRecruitment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.description
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.place
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.stealage_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Date stealageTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.type_id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.picture
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.status
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.create_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage.update_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stealage
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.id
     *
     * @return the value of stealage.id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.id
     *
     * @param id the value for stealage.id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.name
     *
     * @return the value of stealage.name
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.name
     *
     * @param name the value for stealage.name
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.user_id
     *
     * @return the value of stealage.user_id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.user_id
     *
     * @param userId the value for stealage.user_id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.is_recruitment
     *
     * @return the value of stealage.is_recruitment
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Boolean getIsRecruitment() {
        return isRecruitment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.is_recruitment
     *
     * @param isRecruitment the value for stealage.is_recruitment
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setIsRecruitment(Boolean isRecruitment) {
        this.isRecruitment = isRecruitment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.description
     *
     * @return the value of stealage.description
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.description
     *
     * @param description the value for stealage.description
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.place
     *
     * @return the value of stealage.place
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.place
     *
     * @param place the value for stealage.place
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.stealage_time
     *
     * @return the value of stealage.stealage_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Date getStealageTime() {
        return stealageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.stealage_time
     *
     * @param stealageTime the value for stealage.stealage_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setStealageTime(Date stealageTime) {
        this.stealageTime = stealageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.type_id
     *
     * @return the value of stealage.type_id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.type_id
     *
     * @param typeId the value for stealage.type_id
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.picture
     *
     * @return the value of stealage.picture
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.picture
     *
     * @param picture the value for stealage.picture
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.status
     *
     * @return the value of stealage.status
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.status
     *
     * @param status the value for stealage.status
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.create_time
     *
     * @return the value of stealage.create_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.create_time
     *
     * @param createTime the value for stealage.create_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage.update_time
     *
     * @return the value of stealage.update_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage.update_time
     *
     * @param updateTime the value for stealage.update_time
     *
     * @mbg.generated Sun Dec 04 00:21:25 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}