package com.xupt.stealage.model;

import java.io.Serializable;
import java.util.Date;

public class StealageProcessContent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage_process_contents.id
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage_process_contents.stealage_id
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    private Integer stealageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage_process_contents.user_id
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage_process_contents.content
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage_process_contents.create_time
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stealage_process_contents.update_time
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stealage_process_contents
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage_process_contents.id
     *
     * @return the value of stealage_process_contents.id
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage_process_contents.id
     *
     * @param id the value for stealage_process_contents.id
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage_process_contents.stealage_id
     *
     * @return the value of stealage_process_contents.stealage_id
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public Integer getStealageId() {
        return stealageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage_process_contents.stealage_id
     *
     * @param stealageId the value for stealage_process_contents.stealage_id
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public void setStealageId(Integer stealageId) {
        this.stealageId = stealageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage_process_contents.user_id
     *
     * @return the value of stealage_process_contents.user_id
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage_process_contents.user_id
     *
     * @param userId the value for stealage_process_contents.user_id
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage_process_contents.content
     *
     * @return the value of stealage_process_contents.content
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage_process_contents.content
     *
     * @param content the value for stealage_process_contents.content
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage_process_contents.create_time
     *
     * @return the value of stealage_process_contents.create_time
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage_process_contents.create_time
     *
     * @param createTime the value for stealage_process_contents.create_time
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stealage_process_contents.update_time
     *
     * @return the value of stealage_process_contents.update_time
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stealage_process_contents.update_time
     *
     * @param updateTime the value for stealage_process_contents.update_time
     *
     * @mbg.generated Mon Jan 09 23:43:20 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}