package com.xupt.stealage.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.friend_ids
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    private String friendIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.picture
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_time
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.update_time
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.friend_ids
     *
     * @return the value of users.friend_ids
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public String getFriendIds() {
        return friendIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.friend_ids
     *
     * @param friendIds the value for users.friend_ids
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public void setFriendIds(String friendIds) {
        this.friendIds = friendIds == null ? null : friendIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.picture
     *
     * @return the value of users.picture
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.picture
     *
     * @param picture the value for users.picture
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.create_time
     *
     * @return the value of users.create_time
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.create_time
     *
     * @param createTime the value for users.create_time
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.update_time
     *
     * @return the value of users.update_time
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.update_time
     *
     * @param updateTime the value for users.update_time
     *
     * @mbg.generated Mon Jan 09 00:24:42 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}